version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "phoenix_hello"
    depends_on:
      - db
    ports:
      - 4000:4000
    volumes:
      - /var/www:/var/www
    links:
      - db:database
    privileged: true
  db:
    image: "postgres:10.6"
    container_name: "database"
    restart: always
    environment:
      # ユーザーは「postgres」 → PostgerSQLのデフォルトユーザー
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
